main : ${project.groupId}.gameboxx.GameBoxx
name: GameBoxx
version: ${project.version}
description: ${project.description}
author: ${project.author}
authors: ${project.authors}
softdepend: [Vault]
commands:
  arena:
    description: Arena management.
    aliases: [ar, arenas]
  option:
    description: Arena setup options.
    aliases: [set, setoption, options, arenaoption, ao, opt]